# Generated by Django 3.0.4 on 2020-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reviews',
            name='Review',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor_reviews',
            name='Review',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
