# Generated by Django 3.0.4 on 2020-03-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_auto_20200328_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Stars',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='professors',
            old_name='Stars',
            new_name='Ratings',
        ),
    ]
