# Generated by Django 3.0.4 on 2020-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_auto_20200328_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reviews',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professor_reviews',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
